# Generated by Django 5.2.6 on 2026-01-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_studentfeedback_teachernote_urgentcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='behaviorrecord',
            name='subject',
            field=models.CharField(default='General', max_length=100, verbose_name='วิชา'),
        ),
    ]
