# Generated by Django 5.2.6 on 2026-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_privatenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='subject',
            field=models.CharField(default='General', max_length=100, verbose_name='วิชา'),
        ),
    ]
