# Generated by Django 5.2.6 on 2026-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_studentfeedback_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='แนะนำตัว'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='กลุ่มสาระฯ'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อเล่น'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทร'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
    ]
