# Generated by Django 5.2.6 on 2026-01-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='แนะนำตัว'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ห้องเรียน'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='กลุ่มสาระฯ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อเล่น'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
    ]
