# Generated by Django 5.2.6 on 2026-01-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userprofile_bio_userprofile_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('math', 'คณิตศาสตร์'), ('sci', 'วิทยาศาสตร์'), ('eng', 'ภาษาต่างประเทศ'), ('thai', 'ภาษาไทย'), ('soc', 'สังคมศึกษา'), ('art', 'ศิลปะ'), ('pe', 'สุขศึกษาและพลศึกษา'), ('work', 'การงานอาชีพ')], max_length=100, null=True, verbose_name='กลุ่มสาระฯ'),
        ),
    ]
