# Generated by Django 5.2.6 on 2026-01-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeedback',
            name='department',
            field=models.CharField(blank=True, choices=[('math', 'คณิตศาสตร์'), ('sci', 'วิทยาศาสตร์'), ('eng', 'ภาษาต่างประเทศ'), ('thai', 'ภาษาไทย'), ('soc', 'สังคมศึกษา'), ('art', 'ศิลปะ'), ('pe', 'สุขศึกษาและพลศึกษา'), ('work', 'การงานอาชีพ')], max_length=100, null=True, verbose_name='วิชา/กลุ่มสาระ'),
        ),
    ]
