# Generated by Django 5.2.6 on 2026-01-12 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_studentprofile_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='my_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
