# Generated by Django 5.2.6 on 2026-01-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_studentprofile_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, verbose_name='รหัสวิชา')),
                ('subject_name', models.CharField(max_length=200, verbose_name='ชื่อวิชา')),
                ('academic_year', models.CharField(blank=True, max_length=10, verbose_name='ปีการศึกษา')),
                ('semester', models.CharField(blank=True, max_length=10, verbose_name='เทอม')),
                ('score', models.FloatField(default=0.0, verbose_name='คะแนนที่ได้')),
                ('max_score', models.FloatField(default=100.0, verbose_name='คะแนนเต็ม')),
                ('grade', models.CharField(blank=True, max_length=5, null=True, verbose_name='เกรด')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='blog.studentprofile')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
