# Generated by Django 5.2.6 on 2026-02-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_subject_assessment_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='assessment',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='score',
            name='student',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
