# Generated by Django 5.2.6 on 2026-05-15 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_score_assessment_alter_score_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behaviorrecord',
            name='activity_score',
            field=models.IntegerField(default=0, verbose_name='คะแนนกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='behaviorrecord',
            name='attendance_score',
            field=models.IntegerField(default=0, verbose_name='คะแนนเข้าเรียน'),
        ),
        migrations.AlterField(
            model_name='behaviorrecord',
            name='quiz_score',
            field=models.FloatField(default=0.0, error_messages={'blank': 'กรุณากรอกคะแนนควิซ', 'null': 'กรุณากรอกคะแนนควิซ'}, validators=[django.core.validators.MinValueValidator(0.0, message='คะแนนต้องไม่ติดลบ'), django.core.validators.MaxValueValidator(10.0, message='คะแนนควิซต้องไม่เกิน 10 คะแนน')], verbose_name='คะแนนควิซ'),
        ),
    ]
